// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqTT_npRwZFEnKn0toHXWars740v6beo',
    appId: '1:922493230776:web:7efa4e05dbbfd83a991e4d',
    messagingSenderId: '922493230776',
    projectId: 'socialmediaapp-f31bc',
    authDomain: 'socialmediaapp-f31bc.firebaseapp.com',
    storageBucket: 'socialmediaapp-f31bc.firebasestorage.app',
    measurementId: 'G-945365BVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0H__P6aUbC4wrAhsyk36GckaTUIMMa8w',
    appId: '1:922493230776:android:011b5d8dbbc8399c991e4d',
    messagingSenderId: '922493230776',
    projectId: 'socialmediaapp-f31bc',
    storageBucket: 'socialmediaapp-f31bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCusuxpGQ0slZW9MIcx_arBtQyW-l1oZQM',
    appId: '1:922493230776:ios:5eade310ee8b2654991e4d',
    messagingSenderId: '922493230776',
    projectId: 'socialmediaapp-f31bc',
    storageBucket: 'socialmediaapp-f31bc.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCusuxpGQ0slZW9MIcx_arBtQyW-l1oZQM',
    appId: '1:922493230776:ios:5eade310ee8b2654991e4d',
    messagingSenderId: '922493230776',
    projectId: 'socialmediaapp-f31bc',
    storageBucket: 'socialmediaapp-f31bc.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrqTT_npRwZFEnKn0toHXWars740v6beo',
    appId: '1:922493230776:web:8a1c9744fca5eddf991e4d',
    messagingSenderId: '922493230776',
    projectId: 'socialmediaapp-f31bc',
    authDomain: 'socialmediaapp-f31bc.firebaseapp.com',
    storageBucket: 'socialmediaapp-f31bc.firebasestorage.app',
    measurementId: 'G-3LPVKPRSZK',
  );
}
